In [1]:
#ACESS PARTICULAR ELEMENT 

In [2]:
import numpy as np

In [3]:
mx=np.arange(1,101).reshape(10,10)
print(mx)

[[  1   2   3   4   5   6   7   8   9  10]
 [ 11  12  13  14  15  16  17  18  19  20]
 [ 21  22  23  24  25  26  27  28  29  30]
 [ 31  32  33  34  35  36  37  38  39  40]
 [ 41  42  43  44  45  46  47  48  49  50]
 [ 51  52  53  54  55  56  57  58  59  60]
 [ 61  62  63  64  65  66  67  68  69  70]
 [ 71  72  73  74  75  76  77  78  79  80]
 [ 81  82  83  84  85  86  87  88  89  90]
 [ 91  92  93  94  95  96  97  98  99 100]]


# consider it a file with 10 col because we need a file and to red it we use pandas lib 

In [4]:
#elemnt of 1st index row,col
mx[0,0]

1

In [5]:
#the value doesnt shoe ita a array elemnt check dimension
#0=scalar value
mx[0,0].ndim

0

In [6]:
mx[0]
#a row 0 full

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [8]:
mx[0].ndim

1

In [9]:
mx[:,0] #colum

array([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [10]:
mx[:,0 :1] #2dimension

array([[ 1],
       [11],
       [21],
       [31],
       [41],
       [51],
       [61],
       [71],
       [81],
       [91]])

In [11]:
#accs 2 to 4 nd row
#index start from 0
#4 exclusive

mx[1:4,1:4]

array([[12, 13, 14],
       [22, 23, 24],
       [32, 33, 34]])

In [13]:
#all row some col
mx[:,1:3]

array([[ 2,  3],
       [12, 13],
       [22, 23],
       [32, 33],
       [42, 43],
       [52, 53],
       [62, 63],
       [72, 73],
       [82, 83],
       [92, 93]])

In [14]:
#using slicing whole matrix
mx[:] # 0r mx[::] mx[:,:]

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

# item size attribute

In [15]:
#staoge to store item

In [16]:
mx.itemsize #byte 32/8

4

In [17]:
mx.dtype

dtype('int32')

# CONCATINATION AND SPLIT 

In [25]:
#JOIN 
#4 by 4 matrix yani 16 values ka range
mx1=np.arange(1,17).reshape(4,4)
print(mx1)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [23]:
mx2=np.arange(17,33).reshape(4,4)
print(mx2)

[[17 18 19 20]
 [21 22 23 24]
 [25 26 27 28]
 [29 30 31 32]]


In [26]:
#join
mx1 + mx2

array([[18, 20, 22, 24],
       [26, 28, 30, 32],
       [34, 36, 38, 40],
       [42, 44, 46, 48]])

In [28]:
np.concatenate((mx1,mx2))
#takes a tuple to concatinate both
#col wise con means arr1 col ke necchy 2sra col

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24],
       [25, 26, 27, 28],
       [29, 30, 31, 32]])

In [29]:
np.concatenate((mx1,mx2),axis = 1)
#1 repr rowa


array([[ 1,  2,  3,  4, 17, 18, 19, 20],
       [ 5,  6,  7,  8, 21, 22, 23, 24],
       [ 9, 10, 11, 12, 25, 26, 27, 28],
       [13, 14, 15, 16, 29, 30, 31, 32]])

In [32]:
#or use func vertical step 
np.vstack((mx1,mx2))


array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24],
       [25, 26, 27, 28],
       [29, 30, 31, 32]])

In [34]:
#or use func horizonta step 
np.hstack((mx1,mx2))

array([[ 1,  2,  3,  4, 17, 18, 19, 20],
       [ 5,  6,  7,  8, 21, 22, 23, 24],
       [ 9, 10, 11, 12, 25, 26, 27, 28],
       [13, 14, 15, 16, 29, 30, 31, 32]])

In [35]:
np.hstack((mx1,mx2,mx1))

array([[ 1,  2,  3,  4, 17, 18, 19, 20,  1,  2,  3,  4],
       [ 5,  6,  7,  8, 21, 22, 23, 24,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 25, 26, 27, 28,  9, 10, 11, 12],
       [13, 14, 15, 16, 29, 30, 31, 32, 13, 14, 15, 16]])

In [36]:
#split array or kity parts
np.split(mx1,2)
#returns a list of numpy array
#row wise split

[array([[1, 2, 3, 4],
        [5, 6, 7, 8]]), array([[ 9, 10, 11, 12],
        [13, 14, 15, 16]])]

In [37]:
np.split(mx1,2,axis = 1)

[array([[ 1,  2],
        [ 5,  6],
        [ 9, 10],
        [13, 14]]), array([[ 3,  4],
        [ 7,  8],
        [11, 12],
        [15, 16]])]

In [38]:
#creates 1d array and split to 2 variables of 1d arrays
d1=np.array([4,6,2,8,5])

In [41]:
np.split(d1,[1,3])
#list of indexes
#phely array mein 1st index se phele ki values , 2sry mein 3 inex se phele,baki ki last array mein lhud se



[array([4]), array([6, 2]), array([8, 5])]