In [1]:
import numpy as np
#generate data for sample
import random 

In [2]:
np.random.random(1)
#0 to 1 value
#creates an array

array([0.09275677])

In [3]:
#creates 2d require shazpe 
np.random.random((3,3))

array([[0.93371319, 0.1680968 , 0.70491539],
       [0.2966323 , 0.60591874, 0.20822136],
       [0.67791151, 0.4997242 , 0.62500689]])

In [4]:
#to make int valyes takes range as input
np.random.randint(1,4)

3

In [5]:
np.random.randint(1,4,(4,4))
#tuple shape


array([[1, 3, 2, 3],
       [2, 3, 2, 1],
       [3, 3, 3, 3],
       [3, 1, 3, 2]])

In [6]:
np.random.randint(1,4,(2,4,4))

array([[[3, 3, 1, 2],
        [2, 1, 2, 3],
        [1, 1, 2, 1],
        [1, 3, 1, 2]],

       [[1, 3, 1, 3],
        [3, 3, 3, 2],
        [2, 3, 1, 2],
        [1, 3, 1, 2]]])

In [7]:
#har dafa alag alag values 
#to execute same values
np.random.seed(10)
np.random.randint(1,4,(2,4,4))

array([[[2, 2, 1, 1],
        [2, 1, 2, 2],
        [1, 2, 2, 3],
        [1, 2, 1, 3]],

       [[1, 3, 1, 1],
        [1, 3, 1, 3],
        [3, 2, 1, 1],
        [3, 2, 3, 2]]])

In [8]:
#har dafa alag alag values 
#to execute same values
np.random.seed(10)
np.random.randint(1,4,(2,4,4))

array([[[2, 2, 1, 1],
        [2, 1, 2, 2],
        [1, 2, 2, 3],
        [1, 2, 1, 3]],

       [[1, 3, 1, 1],
        [1, 3, 1, 3],
        [3, 2, 1, 1],
        [3, 2, 3, 2]]])

In [9]:
2**32-1 #combinayion

4294967295

In [10]:
np.random.rand(3)
#takes no of elements

array([0.13145815, 0.41366737, 0.77872881])

In [11]:
np.random.rand(3,3)

array([[0.58390137, 0.18263144, 0.82608225],
       [0.10540183, 0.28357668, 0.06556327],
       [0.05644419, 0.76545582, 0.01178803]])

In [12]:
np.random.randn(3,3) #neg and pos

array([[-1.58494101,  1.05535316, -1.92657911],
       [ 0.69858388, -0.74620143, -0.15662666],
       [-0.19363594,  1.13912535,  0.36221796]])

In [14]:
x=[1,2,3,4]
np.random.choice(x)

1

In [15]:
np.random.choice(x)

1

In [16]:
for i in range(20):
  print(np.random.choice(x))
#chosse random number for our choice of list i,e x

1
2
1
4
1
1
3
1
3
3
1
4
2
1
4
2
3
3
2
3


In [19]:
# permutation combination
np.random.permutation(x)

array([1, 4, 2, 3])

In [18]:
np.random.permutation(x)

array([2, 3, 4, 1])

# look scipy.org official website for more funcs