In [1]:
import numpy as np

In [2]:
array1d=np.array([1,2,3,4])
print(array1d)

[1 2 3 4]


In [3]:
#check list or array
type(array1d)

numpy.ndarray

In [4]:
#1d or 2d?
array1d.ndim

1

In [5]:
#create 2d array
array2d=np.array([[1,3,4,2],[1,3,4,2]])
print(array2d)
type(array2d)
array2d.ndim

[[1 3 4 2]
 [1 3 4 2]]


2

In [6]:
#size
array2d.size


8

In [7]:
#shape 
array2d.shape
#return tuple of row,column

(2, 4)

In [8]:
#check data type of array element
array2d.dtype

dtype('int32')

In [9]:
array1d


array([1, 2, 3, 4])

In [10]:
#create identity matrix
onematrix=np.array([[1,1,1],[1,1,1],[1,1,1]])
print(onematrix)


[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [11]:
omx=np.ones(5)
print(omx)

[1. 1. 1. 1. 1.]


In [12]:
#by default 1 row 1 col float 
#send tuple
omx1= np.ones((3,4))
print(omx1)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [13]:
#to make int values
intomx= np.ones((3,4),dtype=int)
print(intomx)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [14]:
ones_arr2 = np.ones((2,3,4)) #creates ndarray of (2,3,4) containing 1's
print(ones_arr2)

[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]


In [15]:
#zero matrix
zerom=np.zeros((3,3))
print(zerom)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [16]:
#change data types
zerom=np.zeros((3,3),dtype=bool)
print(zerom)
zerom=np.zeros((3,3),dtype=str)
print(zerom)

[[False False False]
 [False False False]
 [False False False]]
[['' '' '']
 ['' '' '']
 ['' '' '']]


In [17]:
emstr=""
print(bool(emstr))

False


In [18]:
empmx=np.empty((3,3))
print(empmx)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [28]:
identity_arr1 = np.eye(10) #creates a identity ndarray i.e. containing 1's on leading diagonals and 0's everywhere else
identity_arr1
#identity_arr2 = np.identity(10) #Same as eye ndarray

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

# numpy functions

# arrange()

In [19]:
#np.arange(star,end,steps)
ranmx=np.arange(1,13)
print(ranmx)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [20]:
em=np.arange(1,13,2)
#even array 
print(em)

[ 1  3  5  7  9 11]


# linspace()


In [21]:
linm=np.linspace(1,5,4)
print(linm)

[1.         2.33333333 3.66666667 5.        ]


# reshape 
1d to multi dim


In [22]:
resm=ranmx.reshape(2,6)
print(resm)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


In [23]:
#1 to 3 1=3d 2=2d 3=1d
res3m=ranmx.reshape(2,3,2)
print(res3m)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [24]:
arr=np.arange(1,13).reshape(2,6)
print(arr)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


# ravel multi to 1d

In [25]:
ravm=arr.ravel()
print(ravm)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


# flatten muli to 1d


In [26]:
flam=arr.flatten()
print(flam)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


# TRANSPOSE

In [27]:
ranmx=np.arange(1,13)
resm=ranmx.reshape(2,6)
print(resm)
tram=resm.transpose()
print(tram)
#or name.T

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]
[[ 1  7]
 [ 2  8]
 [ 3  9]
 [ 4 10]
 [ 5 11]
 [ 6 12]]
